### ISSUE TITLE
mac 执行 npm i 提示错误

### ISSUE THREAD

**Issue by wanglemao** [tangerren/Indoor-Map-Draw#1]
错误代码：
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "自定义": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:

**Comment by tangerren** [comment]
删掉  package.json  中的 `devDependencies-@types/ol`

**Comment by wanglemao** [comment]
嗯，可以了，我们现在计划开发一款室内地图的web软件，想用threejs，但是关于地图编辑不知道该怎么做，因为客户给的文件是cad的，大神，有啥推荐的不

**Comment by tangerren** [comment]
> 嗯，可以了，我们现在计划开发一款室内地图的web软件，想用threejs，但是关于地图编辑不知道该怎么做，因为客户给的文件是cad的，大神，有啥推荐的不

CAD  ----->  geojson
