### ISSUE TITLE
项目无法正常显示

### ISSUE THREAD

**Issue by yangding39** [tangerren/Indoor-Map-Draw#2]
项目起来后，无法正常使用功能，样式丢失，图片丢失，请问是什么问题呢，谢谢，以下是截图
![捕获1](https://user-images.githubusercontent.com/1712682/66697010-1c2eec00-ed04-11e9-8865-2fc61ac8d7b1.PNG)
![捕获2](https://user-images.githubusercontent.com/1712682/66697011-1cc78280-ed04-11e9-950d-09768b373ac3.PNG)

**Comment by tangerren** [comment]
找前端人员帮你看下，引用插件、图片路径等问题

**Comment by yangding39** [comment]
我只删除了package.json里得devDependencies-@types/ol，其他没修改直接启动得

**Comment by defineconst** [comment]
@yangding39 
你好。你的问题解决了吗？界面上和你一样，但是没有提示缺少图片的提示。
![image](https://user-images.githubusercontent.com/3112684/124054400-7cc00880-da54-11eb-9939-87883834e6a5.png)
