### ISSUE TITLE
界面异常

### ISSUE THREAD

**Issue by defineconst** [tangerren/Indoor-Map-Draw#21]
@yangding39 
你好。你的问题解决了吗？界面上和你一样，但是没有提示缺少图片的提示。
![image](https://user-images.githubusercontent.com/3112684/124054400-7cc00880-da54-11eb-9939-87883834e6a5.png)

_Originally posted by @defineconst in https://github.com/WoShiSunWuKong/Indoor-Map-Draw/issues/2#issuecomment-871856027_

**Comment by defineconst** [comment]
> indoor-map-draw@0.0.0 start D:\Indoor-Map-Draw-master
> ng serve

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2021-07-01T02:14:33.293Z
Hash: 004fc0733cff9dfb3d72
Time: 11379ms
chunk {common} common.js, common.js.map (common) 3.21 kB  [rendered]
chunk {edit-page-edit-page-module} edit-page-edit-page-module.js, edit-page-edit-page-module.js.map (edit-page-edit-page
-module) 27.8 kB  [rendered]
chunk {main} main.js, main.js.map (main) 39.1 kB [initial] [rendered]
chunk {map-page-map-page-module} map-page-map-page-module.js, map-page-map-page-module.js.map (map-page-map-page-module)
 2.41 MB  [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 231 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 8.92 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.05 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 10 MB [initial] [rendered]

WARNING in ./node_modules/_@angular_core@7.0.3@@angular/core/fesm5/core.js 15153:15-36
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/

WARNING in ./node_modules/_@angular_core@7.0.3@@angular/core/fesm5/core.js 15165:15-102
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
i ｢wdm｣: Compiled with warnings.

谢谢

**Comment by defineconst** [comment]
浏览器日志
ng-zorro-antd.js:1152 [NG-ZORRO] <i class="anticon"></i> would be deprecated soon. Please use <i nz-icon type=""></i> API.
push../node_modules/_ng-zorro-antd@1.8.0@ng-zorro-antd/fesm5/ng-zorro-antd.js.NzIconDirective._warnAPI @ ng-zorro-antd.js:1152
core.js:13689 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
client:148 [WDS] Warnings while compiling.
warnings @ client:148
client:154 ./node_modules/_@angular_core@7.0.3@@angular/core/fesm5/core.js 15153:15-36
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
warnings @ client:154
client:154 ./node_modules/_@angular_core@7.0.3@@angular/core/fesm5/core.js 15165:15-102
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
warnings @ client:154

**Comment by tangerren** [comment]
自行升级下Angular框架，重新组织下代码
