### ISSUE TITLE
看起来做的很好呀，但是请问咋导出geojson呢

### ISSUE THREAD

**Issue by 583** [tangerren/Indoor-Map-Draw#3]
![image](https://user-images.githubusercontent.com/18026534/80659372-64083b80-8abb-11ea-86b2-052d8828b934.png)
请问下，这个没看到可以导出地图的地方呢，文件夹里面也没搜到

**Comment by tangerren** [comment]
还是个半成品，导出功能没有做。感兴趣可自行添加功能

**Comment by defineconst** [comment]
> ![image](https://user-images.githubusercontent.com/18026534/80659372-64083b80-8abb-11ea-86b2-052d8828b934.png)
> 请问下，这个没看到可以导出地图的地方呢，文件夹里面也没搜到
Indoor-Map-Draw 使用npm run start后是这样了。
![image](https://user-images.githubusercontent.com/3112684/124054561-cf012980-da54-11eb-91ab-691c632616b9.png)
知道怎么解决吗？谢谢

**Comment by andyz168** [comment]
> ![image](https://user-images.githubusercontent.com/18026534/80659372-64083b80-8abb-11ea-86b2-052d8828b934.png) 请问下，这个没看到可以导出地图的地方呢，文件夹里面也没搜到

搞了导出没，ng serve 的时候报错了


This version of CLI is only compatible with Angular versions ^15.0.0,
but Angular version 11.0.5 was found instead.

Please visit the link below to find instructions on how to update Angular.
